apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: trek10-namespace-admin-binding
  namespace: trek10
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: namespace-admin
subjects:
- kind: Group
  name: trek10-deploy
  namespace: trek10
